export const profiles =[
    {
        id:'847787',
        userName:'hanalee',
        password:'cocomelon',
        userType:'Student',
        name:{
            firstName:'Analie',
            lastName:'Barbanida',
        },
        course:'BSIT',
        yearSection:'3B',
    },
    {
        id:'1234',
        userName:'Longskie',
        password:'yumyum',
        userType:'Teacher',
        name:{
            firstName:'Clyde',
            lastName:'Espigadera',
        },
        course:'CRIMINOLOGY',
        yearSection:'2A',
    },
    {
        id:'1223',
        userName:'Darkgrey',
        password:'iloveu',
        userType:'Student',
        name:{
            firstName:'Kenneth',
            lastName:'Maramion',
        },
        course:'Engineering',
        yearSection:'2B',
    },
    {
        id:'1222',
        userName:'khimy',
        password:'sunognalaki',
        userType:'Student',
        name:{
            firstName:'Kim',
            lastName:'Untao',
        },
        course:'Media and Communication',
        yearSection:'2C',
    },
    {
        id:'1123',
        userName:'Bebot',
        password:'Homot',
        userType:'Teacher',
        name:{
            firstName:'Bebeth',
            lastName:'Barbanida',
        },
        course:'Education',
        yearSection:'3A',
    },
    {
        id:'1333',
        userName:'Tinay',
        password:'cutipie',
        userType:'Student',
        name:{
            firstName:'Christine',
            lastName:'Escobia',
        },
        course:'Architecture and Design',
        yearSection:'4A',
    },
]